#!/bin/env python
# coding=utf-8
import objects.personne
import objects.acces
import objects.coordonnees
import objects.patient
import objects.medecin
import objects.teste_covid19
import objects.questionnaire
import objects.question
import objects.reponse