import html.html_medecins
#import html.html_acces
#import html.html_coordonnees
#import html.html_patient
#import html.html_medecin
#import html.html_testCovid19
#import html.html_questionnaire
#import html.html_question
#import html.html_reponse